### ISSUE TITLE
Alt+Enter windowed mode borderless?

### ISSUE THREAD

**Issue by noobmaster777** [DrazharLn/pracx#38]
Hi! Firstly thanks so much for this patch. Im trying to play pure smac on a smaller (480x320) screen but the game refuses to go anything below 800x600 on full screen even when I try to change from PRACX options screen height and width. What works is if I press alt+enter so it goes to windowed mode but due to its small size, I need windowed mode to be borderless. Is there a way to make this happen? Thanks

**Comment by induktio** [comment]
The minimum resolution natively supported by the game is 800x600. In this case the patch just uses software scaling to reduce the original image to some smaller size which can make things hard to read. If I recall right the windowed mode always uses bordered windows in this patch. Anyway it is not really recommended since the user interface was designed to use at least 1024x768 resolution.

**Comment by noobmaster777** [comment]
Thanks for your quick response. I will look for another way which does not require to use alt+enter (windowed) but instead to make the full screen fit my screen. Playing with Dwxnd perhaps there is a chance
